## Switches
 set_property PACKAGE_PIN V17 [get_ports {SW0}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {SW0}]
 set_property PACKAGE_PIN V16 [get_ports {SW1}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {SW1}]
 set_property PACKAGE_PIN W16 [get_ports {SW2}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {SW2}]
 set_property PACKAGE_PIN W17 [get_ports {SW3}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {SW3}]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {LD0}]
     set_property IOSTANDARD LVCMOS33 [get_ports {LD0}]
set_property PACKAGE_PIN E19 [get_ports {LD1}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD1}]
set_property PACKAGE_PIN U19 [get_ports {LD2}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD2}]
set_property PACKAGE_PIN V19 [get_ports {LD3}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD3}]
set_property PACKAGE_PIN W18 [get_ports {LD4}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD4}]
set_property PACKAGE_PIN U15 [get_ports {LD5}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD5}]
set_property PACKAGE_PIN U14 [get_ports {LD6}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD6}]
set_property PACKAGE_PIN V14 [get_ports {LD7}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD7}]
set_property PACKAGE_PIN V13 [get_ports {LD8}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD8}]
set_property PACKAGE_PIN V3 [get_ports {LD9}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD9}]
set_property PACKAGE_PIN W3 [get_ports {LD10}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD10}]
set_property PACKAGE_PIN U3 [get_ports {LD11}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {LD11}]
set_property PACKAGE_PIN P3 [get_ports {LD12}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LD12}]
set_property PACKAGE_PIN N3 [get_ports {LD13}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LD13}]
set_property PACKAGE_PIN P1 [get_ports {LD14}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LD14}]
set_property PACKAGE_PIN L1 [get_ports {LD15}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LD15}]


## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
